### ISSUE TITLE
Please explain why Heroku Dashboard needs access

### ISSUE THREAD

**Issue by roschaefer** [Systems-Development-and-Frameworks/TheCodeNinjas#9]
Hey folks,

I got a notification from @christophstach and just wanted to double-check what it is for.

![2020-12-28_14-14](https://user-images.githubusercontent.com/2110676/103216762-188e8180-4917-11eb-8ae9-e79e185f5db0.png)

I'm happy to give you all the permissions you need and I just wanted to know what are the "private information" that Heroku Dashboard is asking for and for which purpose. As far as I can remeber, I always used Heroku on the command line or by pushing to a heroku git remote.

**Comment by christophstach** [comment]
Hi Robert.

I wanted connect heroku with our repository. The reason for that is that heroku automatically can automatically re-deploy an app if a change on github occurs. Like this there is no need for using the cli manually.

On the dashboard i could only choose my personal repositories. For our organization repository i had to request access first.

**Comment by roschaefer** [comment]
Seems @medizinmensch already approved Heroku:

![2020-12-29_17-43](https://user-images.githubusercontent.com/2110676/103299712-709fb380-49fd-11eb-9435-90f83fac8b0b.png)

closing...

**Comment by medizinmensch** [comment]
@roschaefer, sorry that I just allowed the integration. I know Heroku a bit and trust it enough to take care of our test exercises.
